### ISSUE TITLE
Zvooq error

### ISSUE THREAD

**Issue by ruslaniv** [SeregaPru/kodi_zvooq_addon#2]
Плагин перестал работать, постоянно пишет:

![image](https://github.com/SeregaPru/kodi_zvooq_addon/assets/7631314/f2fbb55a-0079-4131-8e6e-edc69c3f787a)

Где смотреть этот лог?

**Comment by ruslaniv** [comment]
Ну по всей видимости вот это

```
2024-06-25 00:07:10.002 T:68332 warning <general>: [---]   \ - - - - - - - - - - - -
2024-06-25 00:07:10.003 T:68332   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
    Error Type: <class 'requests.exceptions.JSONDecodeError'>
    Error Contents: Expecting value: line 1 column 1 (char 0)
    Traceback (most recent call last):
        File "C:\Users\user\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 971, in json
        return complexjson.loads(self.text, **kwargs)
        File "C:\Program Files\Kodi\system\python\Lib\json\__init__.py", line 370, in loads
        return cls(**kw).decode(s)
        File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
        File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
        File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.zvooq\zvooq_plugin.py", line 556, in <module>
        plugin.run()
        File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.zvooq\routing.py", line 130, in run
        self._dispatch(self.path)
        File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.zvooq\routing.py", line 141, in _dispatch
        view_func(**kwargs)
        File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.zvooq\zvooq_plugin.py", line 369, in build_main_playlists
        genres_playlists = client.main_playlists()
        File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.zvooq\zvooq_client.py", line 87, in main_playlists
        res = self.Service.getMainPlaylists()
        File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.zvooq\lib\zvooq_api\service.py", line 251, in getMainPlaylists
        resp = self.sendGet(url, [])
        File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.zvooq\lib\zvooq_api\service.py", line 82, in sendGet
        resp = r.json(strict=False)
        File "C:\Users\user\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 975, in json
        raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
    requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    -->End of Python script error report<--
    
2024-06-25 00:07:10.035 T:68328   error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.zvooq/Playlists
2024-06-25 00:07:10.047 T:54948   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.zvooq/Playlists) failed
```

**Comment by g-metan** [comment]
плагин все ещё не работает, эксепшену (EXCEPTION) предшествует отказ в доступе (403 Forbidden):
024-11-01 10:55:50.732 T:13888   error <general>: Playlist Player: skipping unplayable item: 5, path [plugin://plugin.zvooq/Track/5821946]
2024-11-01 10:55:51.414 T:14716 warning <general>: [---] Zvooq plugin loaded ... (main)
2024-11-01 10:55:51.416 T:14716 warning <general>: [---] quality: SQ
2024-11-01 10:55:51.416 T:14716 warning <general>: [---] !!! zvooq client initialized !!!
2024-11-01 10:55:51.416 T:14716 warning <general>: [---]  
2024-11-01 10:55:51.416 T:14716 warning <general>: [---] /Track/5821947
2024-11-01 10:55:51.416 T:14716 warning <general>: [---] play_track: 5821947
2024-11-01 10:55:51.416 T:14716 warning <general>: [---] {"operationName": "getTracks", "variables": {"ids": ["5821947"]}, "query": "query getTracks($ids: [ID!]!) { getTracks(ids: $ids) { id title duration position hasFlac artists { id title } release { id title date image { src } } } }"}
2024-11-01 10:55:51.527 T:14716 warning <general>: [---] 
2024-11-01 10:55:51.528 T:14716 warning <general>: [---]   / - - - r e q u e s t - -
2024-11-01 10:55:51.528 T:14716 warning <general>: [---]  | code | 200
2024-11-01 10:55:51.528 T:14716 warning <general>: [---]  | resn | OK
2024-11-01 10:55:51.528 T:14716 warning <general>: [---]  | text | {"data":{"getTracks":[{"id":"5821947","title":"Ave Maria No Morro (Live Version)","duration":195,"position":7,"hasFlac":true,"artists":[{"id":"539475","title":"Scorpions"}],"release":{"id":"663328","title":"Live Bites","date":"1995-01-01T00:00:00","image":{"src":"https://cdn-image.zvuk.com/pic?type=release&id=663328&size={size}&hash=94ae19a4-12dd-4dad-82ff-dbd7b4af6f15"}}}]}}
                                                   
2024-11-01 10:55:51.528 T:14716 warning <general>: [---]   \ - - - - - - - - - - - -
2024-11-01 10:55:51.589 T:14716 warning <general>: [---] 
2024-11-01 10:55:51.589 T:14716 warning <general>: [---]   / - - - r e q u e s t - -
2024-11-01 10:55:51.589 T:14716 warning <general>: [---]  | code | 403
2024-11-01 10:55:51.589 T:14716 warning <general>: [---]  | resn | Forbidden
2024-11-01 10:55:51.589 T:14716 warning <general>: [---]  | text | <!DOCTYPE html>
                                                   <html>
                                                   <head>
                                                     <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
                                                   </head>
                                                   <body>
                                                     <script>
                                                       function copy() {
                                                           document.oncopy = function(event) {
                                                               let report = {
                                                                   report: {
                                                                       datetime: "2024-11-01 07:55:51 +0000",
                                                                       ip: "79.139.128.56",
                                                                       id: "ptICBIGonKo1"
                                                                   }
                                                               };
                                                               event.clipboardData.setData("text", JSON.stringify(report));
                                                               event.preventDefault();
                                                           };
                                                           document.execCommand("copy");
                                                       }
                                                     </script>
                                                     <h1 align="center">Forbidden</h1>
                                                     <p align="center">If you are not a bot, please copy the report and send it to our support team.</p>
                                                     <p align="center"><button onclick="copy()">Copy</button></p>
                                                   </body>
                                                   </html>
                                                   
2024-11-01 10:55:51.589 T:14716 warning <general>: [---]   \ - - - - - - - - - - - -
